name: pynalysis
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - curl=7.82.0
  - cycler=0.11.0
  - double-conversion=3.1.5
  - eigen=3.3.7
  - expat=2.4.4
  - ffmpeg=4.2.2
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - h5py=3.6.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9e
  - jsoncpp=1.9.4
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - libcurl=7.82.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libssh2=1.10.0
  - libtasn1=4.16.0
  - libtheora=1.1.1
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - libzip=1.5.1
  - llvm-openmp=12.0.0
  - llvmlite=0.38.0
  - loguru=0.5.3
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.7.1
  - numba=0.55.1
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pathlib=1.0.1
  - pillow=9.0.1
  - pip=21.2.4
  - proj=6.2.1
  - pyparsing=3.0.4
  - python=3.8.13
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tbb=2021.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - utfcpp=3.2.1
  - vtk=9.0.3
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - black==22.3.0
    - click==8.1.3
    - mypy-extensions==0.4.3
    - pathspec==0.9.0
    - platformdirs==2.5.2
    - tomli==2.0.1
    - typing-extensions==4.2.0
