KBT: 0.00411
proteins:
- Ka:
  - 90.9
  - 90.9
  Ke:
  - 90.9
  - 90.9
  PtoAPratio: 1.0
  diffBoundD:
  - 0 
  - 0
  diffBoundS:
  - 0
  - 0
  diffUnbound: 1.0
  eps: 1625
  fixedEnd0: false
  fixedLocationPerMT: null
  freeLength: 0.053
  freeNumber: 400
  fstall: 5.0
  kappa: 300.0
  ko_d:
  - 0.11
  - 0.11
  ko_s:
  - 0.11
  - 0.11
  lambda: 0.25822
  rc: 0.039
  tag: 0
  useBindVol: false
  vmax:
  - 0.0
  - 0.0
  walkOff: false
